### ISSUE TITLE
Different contexes end up in single key

### ISSUE THREAD

**Issue by buraks** [translation/lingui#2]
Hi,

I am using linguijs. We have some strings that translate differently.

For example Sun (star) and Sun (day of the week) translate differently.

We use them like this:

```ts
const a = t({message: "Sun", context: "Star"})
const b = t({message: "Sun", context: "Short for Sunday"})
```

normally, without
```ts
  service: {
    name: 'TranslationIO',
    apiKey: '--redacted--',
  },
```

it was working ok, the po files would have two separate entries so we could translate separately.

Now that we have integrated with Translation.io while in the en.po we get the keys separately with their context. On another language's po file, we have only one of them without the context carried over, therefore on Translation.io we only get one string to translate and the context is not known.

**Comment by didier-84** [comment]
Hi @buraks,

Sorry for the delay. This problem in our service (integrated directly into the Lingui library) has been fixed with our contribution to the [release of Lingui v4.11.2](https://github.com/lingui/js-lingui/releases/tag/v4.11.2).

It is now possible to pass context to Translation.io using the `context` attribute (introduced in Lingui v4) instead of relying on the `id` attribute (which was the only possible way to do so before v4), without breaking the target PO files.

To use this `context` attribute with Translation.io, make sure to upgrade Lingui to version >= 4.11.2 (our integration is in the @lingui/cli package specifically).

Thank you for your understanding.
